### ISSUE TITLE
Duplicate/Old Repositories

### ISSUE THREAD

**Issue by nickswalker** [Ladvien/HM-10#1]
Some other repos tracking this board appear to be old versions of this breakout. Some of them appear higher in Google results than this repo, so it can be confusing to figure which board is up to date. Are these under your control? You should delete them or post a note in the readme pointing here.

https://github.com/SamEA/Bluetooth_Low_Energy
https://github.com/SamEA/HM-10_Bluetooth_Breakout_Board

**Comment by Ladvien** [comment]
Are asking if the SamEA repos are mine?  If so, no they are not.

My boards are found under my namesake.  The current and stable version being v.9.

https://github.com/Ladvien/HM-10

Or you can order them from OSHPark direct: https://oshpark.com/profiles/Ladvien

Any other designs I've no connection with.  I do know several of the listed OSHPark designs were copied from some of my earlier versions and still have their problems, such as improper voltage divider or non-working TX/RX traffic LEDs.  I've contacted a few in attempt to get them to pull their boards or correct them.  But no luck.
